# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fcastCpp <- function(X, innov, ar, ma, mu, h) {
    .Call('_smoots_fcastCpp', PACKAGE = 'smoots', X, innov, ar, ma, mu, h)
}

tfcastCpp <- function(X, innov, epsBoot, ar, ma, mu, h) {
    .Call('_smoots_tfcastCpp', PACKAGE = 'smoots', X, innov, epsBoot, ar, ma, mu, h)
}

cf0Cpp <- function(Xt) {
    .Call('_smoots_cf0Cpp', PACKAGE = 'smoots', Xt)
}

gsmoothCalcCpp <- function(y, v, p, mu, b, bb) {
    .Call('_smoots_gsmoothCalcCpp', PACKAGE = 'smoots', y, v, p, mu, b, bb)
}

gsmoothCalc2Cpp <- function(y, v, p, mu, b, bb) {
    .Call('_smoots_gsmoothCalc2Cpp', PACKAGE = 'smoots', y, v, p, mu, b, bb)
}

