# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fcastCpp <- function(X, innov, beta, alpha, mu, h) {
    .Call('_smoots_fcastCpp', PACKAGE = 'smoots', X, innov, beta, alpha, mu, h)
}

tfcastCpp <- function(X, innov, Fi, beta, alpha, mu, h) {
    .Call('_smoots_tfcastCpp', PACKAGE = 'smoots', X, innov, Fi, beta, alpha, mu, h)
}

arimaSimBootCpp <- function(Fi, beta, alpha, mu, nStart) {
    .Call('_smoots_arimaSimBootCpp', PACKAGE = 'smoots', Fi, beta, alpha, mu, nStart)
}

acovCpp <- function(Xt, lagMax) {
    .Call('_smoots_acovCpp', PACKAGE = 'smoots', Xt, lagMax)
}

seqNum <- function(begin, end) {
    .Call('_smoots_seqNum', PACKAGE = 'smoots', begin, end)
}

cf0Cpp <- function(Xt) {
    .Call('_smoots_cf0Cpp', PACKAGE = 'smoots', Xt)
}

seqCpp <- function(from, to) {
    .Call('_smoots_seqCpp', PACKAGE = 'smoots', from, to)
}

rseqCpp <- function(from, to) {
    .Call('_smoots_rseqCpp', PACKAGE = 'smoots', from, to)
}

factorialCpp <- function(k) {
    .Call('_smoots_factorialCpp', PACKAGE = 'smoots', k)
}

gsmoothCalcCpp <- function(y, v, p, mu, b, bb) {
    .Call('_smoots_gsmoothCalcCpp', PACKAGE = 'smoots', y, v, p, mu, b, bb)
}

gsmoothCalc2Cpp <- function(y, v, p, mu, b, bb) {
    .Call('_smoots_gsmoothCalc2Cpp', PACKAGE = 'smoots', y, v, p, mu, b, bb)
}

